name: Linux Build and Test
on: [push]
jobs:
  gcc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: unix
    strategy:
      matrix:
        symbols:
          - "no"
          - "mem"
    steps:
      - name: Setup Environment
        run: |
          sudo apt-get install tcl8.6-dev libx11-dev xvfb
          mkdir "$HOME/install dir"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure (symbols=${{ matrix.symbols }})
        run: |
            ./configure ${CFGOPT} "--prefix=$HOME/install dir" || (cat config.log && exit 1)
        env:
          CFGOPT: --enable-symbols=${{ matrix.symbols }}
      - name: Build
        run: make binaries libraries
      - name: Build Test Harness
        run: make tktest
      - name: Run Tests
        run: |
          xvfb-run --auto-servernum bash <<EOF
          make test-classic >out-classic.txt
          make test-ttk >out-ttk.txt
          EOF
          cat out-classic.txt out-ttk.txt
          cat out-classic.txt out-ttk.txt | grep -q "Failed	0"
      - name: Test-Drive Installation
        run: make install
      - name: Create Distribution Package
        run: make dist
      - name: Convert Documentation to HTML
          # Needs a Tcl source checkout
          if: false
          run: |
            make html-tk
